/**
 * This manifest comes from the /samples/moby-epub-exploded.
 * It was originally generated by r2-shared-js. We don't support
 * all the features of r2-shared-js, like full metadata and
 * detective cover images from meta fields, so our manifest
 * will not fully match this one.
 *
 * Arbitrary property added for the purpose of the test
 *  - presentation
 */

const mobyEpub2FXLManifest = {
  '@context': 'https://readium.org/webpub-manifest/context.jsonld',
  metadata: {
    '@type': 'http://schema.org/Book',
    title: 'Moby Dick; Or, The Whale',
    identifier: 'http://www.gutenberg.org/2701',
    author: 'Herman Melville',
    language: 'en',
    modified: 'Mon May 10 2021 12:15:05 GMT-0700 (Pacific Daylight Time)',
    rights: 'Public domain in the USA.',
    source: 'https://www.gutenberg.org/files/2701/2701-h/2701-h.htm',
    subject: [
      'Whaling -- Fiction',
      'Sea stories',
      'Psychological fiction',
      'Ship captains -- Fiction',
      'Adventure stories',
      'Mentally ill -- Fiction',
      'Ahab, Captain (Fictitious character) -- Fiction',
      'Whales -- Fiction',
      'Whaling ships -- Fiction',
    ],
    cover: 'item1',
    presentation: {
      layout: 'fixed',
    },
  },
  readingOrder: [
    {
      type: 'application/xhtml+xml',
      href: 'OEBPS/@public@vhost@g@gutenberg@html@files@2701@2701-h@2701-h-0.htm.html',
    },
  ],
};

export default mobyEpub2FXLManifest;
